org: tochinny
app: awssetup
service: messaging
frameworkVersion: "3"

provider:
  name: aws
  stage: ${env:STAGE, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  memorySize: 128
  timeout: 10
  versionFunctions: false
  stackName: "${self:provider.stage}-${self:service}"
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    ACCOUNT_ID: ${env:ACCOUNT_ID}
  stackTags:
    SERVICE: "${self:service}"
    REGION: "${self:provider.region}"
  deploymentBucket:
    name: s3-${self:provider.stage}-${self:provider.region}.${env:ACCOUNT_ID}.deploys.${self:service}

resources:
  Resources:
    OthersSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.region}.${env:ACCOUNT_ID}.sns.${self:service}

  Outputs:
    OthersSNSTopicArn:
      Description: "ARN of the SNS topic"
      Value:
        Ref: OthersSNSTopic
      Export:
        Name: 
          Sub: ${self:provider.region}.${env:ACCOUNT_ID}.sns.${self:service}
