service: aws-app-setup-db

frameworkVersion: "3"

provider:
  name: aws
  stage: ${env:STAGE, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  memorySize: 128
  timeout: 10
  deploymentBucket:
    name: ${self:provider.region}.${env:ACCOUNT_ID}.deploys.${self:service}
  versionFunctions: false
  stackName: "${self:provider.stage}-${self:service}"
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    ACCOUNT_ID: ${env:ACCOUNT_ID}
  stackTags:
    SERVICE: "${self:service}"
    REGION: "${self:provider.region}"

resources:
  Resources:
    todos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage, self:provider.stage}-todos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
