org: tochinny
app: awssetup
service: welcome
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  timeout: 100
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    ACCOUNT_ID: ${env:ACCOUNT_ID}
    NODE_ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  httpApi:
    cors: true
  deploymentBucket:
    name: s3-${self:provider.stage}-${self:provider.region}.${env:ACCOUNT_ID}.deploys.${self:service}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  defaultStage: ${opt:stage, 'dev'}
  # dynamodb:
  #     stages:
  #         - dev
  #     start:
  #         port: 8000
  #         inMemory: true
  #         migrate: true
  #     migration:
  #         dir: offline/db/migrations
  serverless-offline:
    ignoreJWTSignature: true
    httpPort: 3001
    websocketPort: 3012
    lambdaPort: 3201

# functions
functions:
  hello:
    handler: src/hello.handler
    events: # The events that trigger this function
      - http: 
          path: awsnodetypescriptsetup/hello
          method: get
  goodbye:
    handler: src/goodbye.handler
    events:
      - http: 
          path: awsnodetypescriptsetup/goodbye
          method: post

